# Generated by Django 4.1.4 on 2022-12-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='media')),
                ('pincode', models.CharField(max_length=6)),
                ('phonenumber', models.CharField(max_length=10)),
            ],
        ),
    ]
