# Generated by Django 4.1.4 on 2022-12-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_app', '0002_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
