# Generated by Django 4.1.4 on 2022-12-26 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pancard',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid  Pan number', regex='[A-Z]{5}[0-9]{4}[A-Z]{1}')]),
        ),
    ]
