# Generated by Django 4.1.4 on 2022-12-26 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate_app', '0003_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(message='Please Enter Only capital Letters', regex='[A-Z]{20}')]),
        ),
    ]
